environment:
  matrix:
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python34-x64"
      DISTUTILS_USE_SDK: "1"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"

build: off

build_script:
  - "%PYTHON%\\python.exe setup.py build"

test_script:
  - "%PYTHON%\\python.exe test/run_tests.py"
